name: CI

on: [push]

jobs:
  prettier:
    name: Prettier Styles
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "yarn"

      - name: Install dependencies
        run: cd file_service && yarn install

      - name: Run Prettier
        run: yarn prettier:format

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Prettier
          branch: ${{ github.head_ref }}

#  tests:
#    name: Unit Test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out git repository
#        uses: actions/checkout@v4
#
#      - name: Set up Nodejs
#        uses: actions/setup-node@v4
#        with:
#          node-version: "21"
#          cache: "yarn"
#
#      - name: Install dependencies
#        run: yarn install
#
#      - name: Unit test
#        run: yarn test